import { Preset } from './types';

export const COMPOSITIONS = ["None","Rule of Thirds","Centered","Leading Lines","Over-the-shoulder","Wide Establishing","Tight Close-up","Low Angle Hero","Top-down Flat Lay","Candid Snapshot","Asymmetric Framing","Peek-through","Symmetrical Arch","Layered Depth"];

export const CAMERAS = [
  "None",
  // Modern Mirrorless / Digital
  "Sony Alpha 1","Canon EOS R3","Nikon Z9","Sony A7 IV","Sony A7R V","Canon EOS R5 II","Nikon Z5 II","Fujifilm X-T5","Fujifilm GFX 100S II","Hasselblad X2D 100C","Phase One XF IQ4","Leica SL3","iPhone 16 Pro","Hasselblad H6D","Nikon D850","Canon EOS 5D Mark IV","DJI Mavic 3",
  // Cinema Digital
  "Arri Alexa 35","Arri Alexa LF","Red V-Raptor","Arri Alexa 65",
  // 35mm Film Rangefinders & SLRs
  "Leica M3", "Leica M6", "Nikon F3", "Nikon F5", "Nikon F6", "Canon EOS 1v", "Contax T2", "Ricoh GR21", "Canon Rangefinder",
  // Medium Format Film
  "Rolleiflex 2.8F", "Hasselblad 500C/M", "Pentax 67", "Pentax 645", "Mamiya RZ67",
  // Large Format & Press
  "Speed Graphic 4x5", "Deardorff 8x10", "Large Format 4x5", "Large Format 8x10", "Voigtländer Bergheil", "Graflex Series D",
  // Cinema Film
  "Arriflex 35 BL", "Arricam ST", "Panavision PSR", "Mitchell BNC", "Technicolor 3-Strip Camera", "IMAX 15/65",
  // Vintage / Specialty
  "Polaroid SX-70", "Sony VX1000", "Contact Print"
];

export const LENSES_BY_GENRE: Record<string, string[]> = {
  portrait: [
    "35mm env", "50mm prime", "85mm prime", "105mm prime", "135mm prime", "70-200mm zoom",
    "35mm prime", "80mm prime", "116mm prime", "120mm macro", "150mm prime", "300mm prime", "360mm prime"
  ],
  street: [
    "24mm prime", "28mm prime", "35mm prime", "50mm prime", "24-70mm zoom",
    "38mm prime", "45-85mm zoom", "80mm prime", "90mm tele", "105mm prime", "127mm Ektar"
  ],
  landscape: [
    "14-24mm wide", "16-35mm wide", "24mm prime", "24-70mm zoom", "70-200mm tele", 
    "50mm prime", "150mm prime", "300mm prime", "300mm prime (8x10 eq)"
  ],
  product: [
    "50mm prime", "85mm prime", "60mm macro", "100mm macro", "90mm tilt-shift",
    "80mm prime", "90mm prime", "120mm macro", "150mm prime", "210mm prime"
  ],
  cinematic: [
    "24mm prime", "35mm prime", "50mm prime", "85mm prime", "40mm anamorphic", "75mm anamorphic",
    "14mm prime", "18mm prime", "32mm prime", "45mm wide", "55mm wide", "35mm anamorphic", "50mm anamorphic", "80mm prime", "300mm tele"
  ],
  night: [
    "24mm prime", "35mm prime", "50mm prime", "85mm prime",
    "35mm anamorphic", "105mm prime", "127mm Ektar"
  ],
  sports: [
    "70-200mm zoom", "100-400mm tele", "300mm prime", "400mm prime",
    "24-70mm zoom", "80mm prime", "200mm prime", "300mm tele", "600mm prime"
  ],
  wildlife: [
    "100-400mm tele", "200-600mm super-tele", "400mm prime", "600mm prime",
    "16mm fisheye", "16-35mm wide", "24-70mm zoom", "100mm macro", "105mm prime", "105mm macro"
  ],
  architecture: [
    "14-24mm wide", "16-35mm wide", "24mm tilt-shift", "17mm tilt-shift",
    "24-70mm zoom", "28mm wide", "45mm tilt-shift", "50mm wide", "90mm wide", "90mm wide (8x10 eq)", "150mm prime"
  ],
  experimental: [
     "8mm fisheye", "50mm prime", "45mm tilt-shift", "None"
  ]
};

export const APERTURES = ["None","f/0.7","f/1.2","f/1.4","f/1.8","f/2","f/2.8","f/4","f/4.5","f/5.6","f/8","f/11","f/16","f/22","f/32","f/45","f/64"];
export const SHUTTERS = ["None","Bulb","30s","15s","8s","4s","2s","1s","1/2s","1/4s","1/8s","1/15s","1/30s","1/48s","1/60s","1/125s","1/160s","1/200s","1/250s","1/320s","1/500s","1/1000s","1/1250s","1/2000s","1/4000s"];
export const ISOS = ["None","1","3","5","10","25","50","64","100","200","400","500","800","1600","3200","6400"];
export const LIGHTINGS = ["None","Natural Light","Soft Overcast","Golden Hour","Studio Softbox","High Key White Cyc","Hard Strobe","Direct Flash","Neon Practical","Candlelight","Stadium Lights","Underwater Ambient"];
export const FILMS = ["None","Kodak Portra 400","Kodak Portra 160","Fuji Pro 400H","Cinestill 800T","Kodak Tri-X B&W","Kodak Gold 400","Kodak Ektachrome","Ilford HP5","Kodak Vision3 500T", "Kodak Vision3 250D", "Kodak Vision3 200T", "Kodachrome 64", "Fujichrome Velvia", "Wet Plate Collodion", "Nitrate Film", "B&W Sheet Film", "Polaroid 600", "Polaroid Type 55", "Technicolor Three-Strip", "Autochrome Plate", "Kodak Aerochrome", "Digital Video Tape", "B&W Negative", "Digital"];
export const GRAINS = ["None","Clean/No Grain","Subtle Grain","Medium Texture","Heavy Grit"];
export const LENS_CHARS = ["None","Clinical Sharp","Vintage Softness","Dreamy Bloom","Gentle Halation","Heavy Vignette", "Swirly Bokeh", "Petzval Curvature"];
export const WBS = ["None","Daylight Balanced","Warm Tungsten","Cool Shade","Mixed Lighting"];

export const LIGHTING_SETUPS = [
  { label: "Softbox Key", phrase: "45 degree softbox key, white bounce fill" },
  { label: "Dual Softbox", phrase: "dual softbox symmetric lighting" },
  { label: "Top Scrim", phrase: "top down scrim, negative fill" },
  { label: "Rim Light", phrase: "strip rim light, edge definition" },
  { label: "Clamshell", phrase: "clamshell beauty lighting" },
  { label: "White Cyc", phrase: "high key white cyc, even wraparound light" },
  { label: "Cross Polarized", phrase: "cross-polarized lighting to control reflections" },
  { label: "Gradient Sweep", phrase: "gradient sweep background, tabletop product lighting" },
  { label: "Hard Flash", phrase: "hard direct flash, fast falloff shadows" },
  { label: "Window Side", phrase: "window side light, soft falloff" },
  { label: "Underwater", phrase: "underwater strobe fill, particle sparkle" },
  { label: "Backlit", phrase: "backlit translucent diffusion, soft halos" },
  { label: "Atmospheric", phrase: "atmospheric smoke and light shafts" },
  { label: "Neon Spill", phrase: "neon sign spill" },
  { label: "Stadium", phrase: "stadium top light, crisp action freeze" },
  { label: "Ring Light", phrase: "ring light fill" },
  { label: "Practical", phrase: "practical lighting" },
  { label: "High Contrast", phrase: "high contrast rim lighting" }
];

export const PRESETS: Preset[] = [
  { id:"leiter-street", title:"Saul Leiter", category:"Street", desc:"Reflections, layered color panes.", data:{ genre:"street", camera:"Leica M3", lens:"90mm tele", focal:90, aperture:"f/4", shutter:"1/60s", iso:"100", lighting:"Natural Light", composition:"Candid Snapshot", lightingSetups:["window side light, soft falloff"], vibe:"Saul Leiter style, shooting through windows and rain-specked glass, stacked reflections, soft focus edges, muted reds and ambers, street scenes as abstract color blocks with a human silhouette implied.", lensChar:"Vintage Softness", film:"Kodachrome 64", wb:"Daylight Balanced", grain:"Subtle Grain" } },
  { id:"maier-doc", title:"Vivian Maier", category:"Street", desc:"Observational candid, sharp moments.", data:{ genre:"street", camera:"Rolleiflex 2.8F", lens:"80mm prime", focal:80, aperture:"f/8", shutter:"1/250s", iso:"100", lighting:"Soft Overcast", composition:"Rule of Thirds", vibe:"Vivian Maier style, candid pedestrian life, clean geometry, mirror and shadow play, decisive everyday moments, waist-level perspective.", lensChar:"Clinical Sharp", film:"Kodak Tri-X B&W", wb:"Daylight Balanced", grain:"Medium Texture" } },
  { id:"cartier-bresson", title:"Henri Cartier-Bresson", category:"Street", desc:"The decisive moment.", data:{ genre:"street", camera:"Leica M3", lens:"50mm prime", focal:50, aperture:"f/8", shutter:"1/125s", iso:"100", lighting:"Natural Light", composition:"Leading Lines", vibe:"Henri Cartier-Bresson style, decisive moment timing, balanced negative space, geometric street composition.", lensChar:"Vintage Softness", film:"Kodak Tri-X B&W", wb:"Daylight Balanced", grain:"Subtle Grain" } },
  { id:"moriyama-flash", title:"Daido Moriyama", category:"Street", desc:"High contrast grit.", data:{ genre:"street", camera:"Ricoh GR21", lens:"28mm prime", focal:28, aperture:"f/11", shutter:"1/60s", iso:"1600", lighting:"Direct Flash", composition:"Tight Close-up", lightingSetups:["hard direct flash, fast falloff shadows"], vibe:"Daido Moriyama style, aggressive close range flash, blur and grain embraced, high contrast blacks, cropped bodies and signage, restless night street energy.", lensChar:"Vintage Softness", film:"Kodak Tri-X B&W", wb:"Mixed Lighting", grain:"Heavy Grit" } },
  { id:"eggleston-color", title:"William Eggleston", category:"Street", desc:"Saturated color, mundane iconic.", data:{ genre:"street", camera:"Leica M3", lens:"50mm prime", focal:50, aperture:"f/8", shutter:"1/250s", iso:"100", lighting:"Natural Light", composition:"Rule of Thirds", vibe:"William Eggleston style, vivid but believable color, quiet mundane subjects, southern daylight, dye-transfer print look.", lensChar:"Vintage Softness", film:"Kodachrome 64", wb:"Daylight Balanced", grain:"Subtle Grain" } },
  { id:"webb-layered", title:"Alex Webb", category:"Street", desc:"Dense frames, hot color, shadows.", data:{ genre:"street", camera:"Leica M6", lens:"35mm prime", focal:35, aperture:"f/8", shutter:"1/500s", iso:"100", lighting:"Natural Light", composition:"Layered Depth", vibe:"Alex Webb style, complex multi-subject street scenes, saturated color in harsh light, deep shadow zones.", lensChar:"Clinical Sharp", film:"Kodachrome 64", wb:"Daylight Balanced", grain:"Subtle Grain" } },
  { id:"weegee-noir", title:"Weegee", category:"Street", desc:"Hard flash night noir.", data:{ genre:"night", camera:"Speed Graphic 4x5", lens:"127mm Ektar", focal:127, aperture:"f/8", shutter:"1/200s", iso:"100", lighting:"Direct Flash", composition:"Tight Close-up", lightingSetups:["hard direct flash, fast falloff shadows"], vibe:"Weegee style, hard on-camera flash, gritty nocturnal realism, high contrast blacks, crime scene aesthetic.", lensChar:"Vintage Softness", film:"Kodak Tri-X B&W", wb:"Mixed Lighting", grain:"Heavy Grit" } },
  { id:"mccurry-travel", title:"Steve McCurry", category:"Street", desc:"Vivid travel portraits.", data:{ genre:"street", camera:"Nikon F6", lens:"105mm prime", focal:105, aperture:"f/2.8", shutter:"1/250s", iso:"64", lighting:"Natural Light", composition:"Rule of Thirds", vibe:"Steve McCurry style, saturated yet believable color, intimate travel portraiture, strong eye contact, warm daylight, Kodachrome aesthetic.", lensChar:"Clinical Sharp", film:"Kodachrome 64", wb:"Daylight Balanced", grain:"Subtle Grain" } },
  { id:"salgado-humanity", title:"Sebastião Salgado", category:"Street", desc:"Dramatic B&W documentary.", data:{ genre:"street", camera:"Pentax 645", lens:"45-85mm zoom", focal:45, aperture:"f/8", shutter:"1/250s", iso:"400", lighting:"Natural Light", composition:"Rule of Thirds", vibe:"High-contrast humanist reportage, strong silhouettes, epic scale, deep blacks and rich mid-tones, silver gelatin print look.", lensChar:"Clinical Sharp", film:"Kodak Tri-X B&W", wb:"Daylight Balanced", grain:"Medium Texture" } },
  { id:"lindbergh-raw", title:"Peter Lindbergh", category:"Portrait & Fashion", desc:"Raw black and white realism.", data:{ genre:"portrait", camera:"Nikon F5", lens:"85mm prime", focal:85, aperture:"f/2.8", shutter:"1/250s", iso:"400", lighting:"Soft Overcast", composition:"Centered", lightingSetups:["window side light, soft falloff"], vibe:"Peter Lindbergh style, raw emotive portrait realism, natural skin texture, minimal retouch, strong eye contact, wind-blown hair, coastal or industrial backdrops, classic monochrome contrast.", lensChar:"Vintage Softness", film:"Kodak Tri-X B&W", wb:"Daylight Balanced", grain:"Subtle Grain" } },
  { id:"penn-studio", title:"Irving Penn", category:"Portrait & Fashion", desc:"Sculptural minimal portrait.", data:{ genre:"portrait", camera:"Deardorff 8x10", lens:"300mm prime", focal:300, aperture:"f/32", shutter:"1/2s", iso:"25", lighting:"Studio Softbox", composition:"Centered", lightingSetups:["clamshell beauty lighting"], vibe:"Irving Penn style, minimalist studio portrait, sculptural shadows, tactile fabric and skin detail, neutral backdrops, platinum print quality.", lensChar:"Clinical Sharp", film:"Kodak Tri-X B&W", wb:"Daylight Balanced", grain:"Clean/No Grain" } },
  { id:"weir-soft", title:"Harley Weir", category:"Portrait & Fashion", desc:"Soft daylight, intimate.", data:{ genre:"portrait", camera:"Pentax 67", lens:"105mm prime", focal:105, aperture:"f/2.4", shutter:"1/125s", iso:"400", lighting:"Natural Light", composition:"Leading Lines", lightingSetups:["window side light, soft falloff"], vibe:"Harley Weir style, soft natural light, intimate close distance, gentle color, slight blur or bloom allowed, candid energy, editorial but lived-in mood.", lensChar:"Dreamy Bloom", film:"Fuji Pro 400H", wb:"Daylight Balanced", grain:"Subtle Grain" } },
  { id:"leibovitz-celeb", title:"Annie Leibovitz", category:"Portrait & Fashion", desc:"Theatrical staged storytelling.", data:{ genre:"cinematic", camera:"Hasselblad 500C/M", lens:"80mm prime", focal:80, aperture:"f/5.6", shutter:"1/60s", iso:"400", lighting:"Studio Softbox", composition:"Centered", lightingSetups:["softbox key plus bounce"], vibe:"Annie Leibovitz style, cinematic celebrity portraiture, strong storytelling through set and light, rich color, confident subjects in staged environments.", lensChar:"Clinical Sharp", film:"Kodak Portra 400", wb:"Daylight Balanced", grain:"Subtle Grain" } },
  { id:"avedon-highkey", title:"Richard Avedon", category:"Portrait & Fashion", desc:"White background, crisp gestures.", data:{ genre:"portrait", camera:"Deardorff 8x10", lens:"360mm prime", focal:360, aperture:"f/22", shutter:"1/60s", iso:"100", lighting:"High Key White Cyc", composition:"Centered", lightingSetups:["high key white cyc, even wraparound light"], vibe:"Richard Avedon style, high-key white cyc fashion portraits, sharp edges, expressive movement, clean modern contrast, dark edges of the negative visible.", lensChar:"Clinical Sharp", film:"Kodak Tri-X B&W", wb:"Daylight Balanced", grain:"Clean/No Grain" } },
  { id:"newton-edgy", title:"Helmut Newton", category:"Portrait & Fashion", desc:"Hard light luxury provocation.", data:{ genre:"portrait", camera:"Hasselblad 500C/M", lens:"80mm prime", focal:80, aperture:"f/8", shutter:"1/125s", iso:"100", lighting:"Hard Strobe", composition:"Rule of Thirds", lightingSetups:["strip rim light, edge definition"], vibe:"Helmut Newton style, hard directional light, glossy high-contrast fashion, controlled provocation, sculpted bodies and luxury attitude.", lensChar:"Clinical Sharp", film:"Kodak Ektachrome", wb:"Daylight Balanced", grain:"Subtle Grain" } },
  { id:"platon-close", title:"Platon", category:"Portrait & Fashion", desc:"Intense wide close-ups.", data:{ genre:"portrait", camera:"Hasselblad 500C/M", lens:"120mm macro", focal:120, aperture:"f/16", shutter:"1/250s", iso:"100", lighting:"Studio Softbox", composition:"Centered", lightingSetups:["clamshell beauty lighting"], vibe:"Platon style, tight symmetrical headshots, bold eye contact, sculpted studio light, graphic simplicity.", lensChar:"Clinical Sharp", film:"Kodak Tri-X B&W", wb:"Daylight Balanced", grain:"Clean/No Grain" } },
  { id:"goldin-diary", title:"Nan Goldin", category:"Portrait & Fashion", desc:"Diaristic flash, warm interiors.", data:{ genre:"night", camera:"Leica M6", lens:"35mm prime", focal:35, aperture:"f/8", shutter:"1/60s", iso:"400", lighting:"Direct Flash", composition:"Candid Snapshot", lightingSetups:["hard direct flash, fast falloff shadows"], vibe:"Nan Goldin style, diaristic nightlife portraiture, emotional immediacy, on-camera flash, warm mixed interiors, Cibachrome print look.", lensChar:"Vintage Softness", film:"Kodak Gold 400", wb:"Warm Tungsten", grain:"Heavy Grit" } },
  { id:"dijkstra-env", title:"Rineke Dijkstra", category:"Portrait & Fashion", desc:"Calm frontal daylight.", data:{ genre:"portrait", camera:"Large Format 4x5", lens:"150mm prime", focal:150, aperture:"f/11", shutter:"1/60s", iso:"100", lighting:"Soft Overcast", composition:"Centered", vibe:"Rineke Dijkstra style, restrained environmental portraits, frontal compositions, soft natural light, quiet stillness, detailed background context.", lensChar:"Clinical Sharp", film:"Kodak Portra 160", wb:"Daylight Balanced", grain:"Subtle Grain" } },
  { id:"testino-fashion", title:"Mario Testino", category:"Portrait & Fashion", desc:"High-glam editorial polish.", data:{ genre:"portrait", camera:"Canon EOS 5D Mark IV", lens:"70-200mm zoom", focal:85, aperture:"f/5.6", shutter:"1/200s", iso:"100", lighting:"Studio Softbox", composition:"Rule of Thirds", lightingSetups:["45 degree softbox key, white bounce fill","strip rim light, edge definition"], vibe:"Mario Testino style, polished high fashion portraiture, confident energy, clean glamour lighting, bright editorial color.", lensChar:"Clinical Sharp", film:"Digital", wb:"Daylight Balanced", grain:"Clean/No Grain" } },
  { id:"weber-romance", title:"Bruce Weber", category:"Portrait & Fashion", desc:"Airy romance, soft grain.", data:{ genre:"portrait", camera:"Pentax 67", lens:"105mm prime", focal:105, aperture:"f/2.4", shutter:"1/125s", iso:"400", lighting:"Golden Hour", composition:"Rule of Thirds", vibe:"Bruce Weber style, breezy sunlit romance, candid youth, gentle haze, warm tones, understated grain and intimacy, B&W or soft color.", lensChar:"Vintage Softness", film:"Kodak Tri-X B&W", wb:"Daylight Balanced", grain:"Subtle Grain" } },
  { id:"walker-surreal", title:"Tim Walker", category:"Portrait & Fashion", desc:"Whimsical theatrical surrealism.", data:{ genre:"cinematic", camera:"Pentax 67", lens:"45mm wide", focal:45, aperture:"f/5.6", shutter:"1/60s", iso:"400", lighting:"Studio Softbox", composition:"Asymmetric Framing", lightingSetups:["dual softbox symmetric lighting"], vibe:"Tim Walker style, whimsical surreal fashion staging, oversized props, theatrical scale, dreamy pastel or jewel palette, gentle bloom.", lensChar:"Dreamy Bloom", film:"Kodak Portra 400", wb:"Daylight Balanced", grain:"Subtle Grain" } },
  { id:"sherman-concept", title:"Cindy Sherman", category:"Portrait & Fashion", desc:"Conceptual constructed identity.", data:{ genre:"portrait", camera:"Nikon F3", lens:"50mm prime",focal:50,aperture:"f/8",shutter:"1/125s",iso:"100",lighting:"Studio Softbox",composition:"Centered",lightingSetups:["softbox key plus bounce"],vibe:"Cindy Sherman style, carefully staged conceptual portrait, performative identity, cinematic disguise, controlled studio light.",lensChar:"Clinical Sharp",film:"Kodak Portra 160",wb:"Daylight Balanced",grain:"Subtle Grain" } },
  { id:"bourdin-surreal", title:"Guy Bourdin", category:"Portrait & Fashion", desc:"Bold color, surreal fashion.", data:{ genre:"cinematic", camera:"Pentax 67", lens:"55mm wide",focal:55,aperture:"f/11",shutter:"1/125s",iso:"100",lighting:"Hard Strobe",composition:"Asymmetric Framing",lightingSetups:["strip rim light, edge definition"],vibe:"Guy Bourdin style, surreal fashion narrative, bold saturated color, strong graphic composition, uncanny poses and props, high-contrast studio light.",lensChar:"Clinical Sharp",film:"Kodak Ektachrome",wb:"Mixed Lighting",grain:"Subtle Grain" } },
  { id:"deakins-cine", title:"Roger Deakins", category:"Cinematic", desc:"Naturalistic film precision.", data:{ genre:"cinematic", camera:"Arri Alexa 35", lens:"32mm prime", focal:32, aperture:"f/2.8", shutter:"1/48s", iso:"800", lighting:"Neon Practical", composition:"Leading Lines", lightingSetups:["window side light, soft falloff"], vibe:"Roger Deakins style, grounded cinematic realism, subtle contrast, motivated practical light, careful negative fill, clean compositions, atmospheric depth without exaggeration.", lensChar:"Clinical Sharp", film:"Kodak Vision3 500T", wb:"Mixed Lighting", grain:"Subtle Grain" } },
  { id:"doyle-neon", title:"Christopher Doyle", category:"Cinematic", desc:"Neon wash, rain, handheld.", data:{ genre:"cinematic", camera:"Arriflex 35 BL", lens:"32mm prime", focal:32, aperture:"f/2", shutter:"1/48s", iso:"500", lighting:"Neon Practical", composition:"Rule of Thirds", vibe:"Christopher Doyle style, saturated neon color wash, rainy streets, handheld intimacy, motion blur as emotion, step printing effect.", lensChar:"Vintage Softness", film:"Kodak Vision3 500T", wb:"Mixed Lighting", grain:"Medium Texture" } },
  { id:"crewdson-tableau", title:"Gregory Crewdson", category:"Cinematic", desc:"Staged suburban eeriness.", data:{ genre:"cinematic", camera:"Phase One XF IQ4", lens:"35mm prime", focal:35, aperture:"f/11", shutter:"1/2s", iso:"100", lighting:"Natural Light", composition:"Wide Establishing", lightingSetups:["softbox key plus bounce"], vibe:"Gregory Crewdson style, staged cinematic suburbia, eerie calm, fog or haze, practical motivated light, meticulous tableau framing, high budget production design.", lensChar:"Clinical Sharp", film:"Kodak Portra 400", wb:"Mixed Lighting", grain:"Subtle Grain" } },
  { id:"anderson-symmetry", title:"Wes Anderson", category:"Cinematic", desc:"Symmetrical, pastel, flat.", data:{ genre:"cinematic", camera:"Arricam ST", lens:"40mm anamorphic", focal:40, aperture:"f/5.6", shutter:"1/48s", iso:"200", lighting:"Soft Overcast", composition:"Symmetrical Arch", lightingSetups:["high key white cyc, even wraparound light"], vibe:"Wes Anderson style (Robert Yeoman), perfectly symmetrical composition, flat planar staging, pastel color palette, whimsical attention to detail, soft even lighting, storybook aesthetic.", lensChar:"Clinical Sharp", film:"Kodak Vision3 200T", wb:"Daylight Balanced", grain:"Clean/No Grain" } },
  { id:"kubrick-perspective", title:"Stanley Kubrick", category:"Cinematic", desc:"One-point perspective, clinical.", data:{ genre:"cinematic", camera:"Arriflex 35 BL", lens:"18mm prime", focal:18, aperture:"f/0.7", shutter:"1/48s", iso:"100", lighting:"Candlelight", composition:"Centered", lightingSetups:["practical lighting"], vibe:"Stanley Kubrick style, obsessive one-point perspective, clinical detachment, deep focus or extreme shallow (Barry Lyndon), Steadicam fluidity, uncanny symmetry, cold or high-contrast practical lighting.", lensChar:"Clinical Sharp", film:"Kodak Vision3 500T", wb:"Cool Shade", grain:"Subtle Grain" } },
  { id:"fraser-darkness", title:"Greig Fraser", category:"Cinematic", desc:"Modern dark epic (Dune/Batman).", data:{ genre:"cinematic", camera:"Arri Alexa LF", lens:"50mm prime", focal:50, aperture:"f/1.8", shutter:"1/48s", iso:"1600", lighting:"Soft Overcast", composition:"Rule of Thirds", lightingSetups:["soft top down ambient"], vibe:"Greig Fraser style, modern dark epic cinematography, soft falloff, rich blacks, textured shadows, atmospheric haze, grounded sci-fi realism, anamorphic depth.", lensChar:"Vintage Softness", film:"Kodak Vision3 500T", wb:"Daylight Balanced", grain:"Medium Texture" } },
  { id:"hoytema-imax", title:"Hoyte van Hoytema", category:"Cinematic", desc:"IMAX scale, grounded reality.", data:{ genre:"cinematic", camera:"IMAX 15/65", lens:"80mm prime", focal:80, aperture:"f/4", shutter:"1/48s", iso:"50", lighting:"Natural Light", composition:"Low Angle Hero", lightingSetups:["huge soft natural sources"], vibe:"Hoyte van Hoytema style (Christopher Nolan), massive IMAX scale, shallow depth of field on large format, grounded reality, practical effects, tactile texture, muted color palette.", lensChar:"Clinical Sharp", film:"Kodak Vision3 500T", wb:"Daylight Balanced", grain:"Subtle Grain" } },
  { id:"scott-atmosphere", title:"Ridley Scott", category:"Cinematic", desc:"Atmospheric shafts of light.", data:{ genre:"cinematic", camera:"Red V-Raptor", lens:"35mm prime", focal:35, aperture:"f/4", shutter:"1/48s", iso:"800", lighting:"Hard Strobe", composition:"Layered Depth", lightingSetups:["atmospheric smoke and light shafts"], vibe:"Ridley Scott style, dense atmospheric layering, smoke and haze, distinct shafts of light (god rays), high detail production design, high contrast, blue/orange color separation.", lensChar:"Clinical Sharp", film:"Fuji Pro 400H", wb:"Mixed Lighting", grain:"Medium Texture" } },
  { id:"lubezki-natural", title:"Emmanuel Lubezki", category:"Cinematic", desc:"Immersive natural light.", data:{ genre:"cinematic", camera:"Arri Alexa 65", lens:"14mm prime", focal:14, aperture:"f/2.8", shutter:"1/48s", iso:"800", lighting:"Natural Light", composition:"Wide Establishing", vibe:"Emmanuel Lubezki style, available-light realism, wide-lens proximity, soft backlight haze, handheld presence, long-take feeling, Malick/Inarritu aesthetic.", lensChar:"Vintage Softness", film:"Kodak Vision3 500T", wb:"Daylight Balanced", grain:"Subtle Grain" } },
  { id:"storaro-period", title:"Vittorio Storaro", category:"Cinematic", desc:"Rich period color.", data:{ genre:"cinematic", camera:"Arriflex 35 BL", lens:"50mm prime", focal:50, aperture:"f/2.8", shutter:"1/48s", iso:"200", lighting:"Candlelight", composition:"Centered", lightingSetups:["backlit translucent diffusion, soft halos"], vibe:"Vittorio Storaro style, dramatic chiaroscuro, warm practical sources, saturated period palette, deep blacks with painterly light contour.", lensChar:"Dreamy Bloom", film:"Kodak Vision3 200T", wb:"Warm Tungsten", grain:"Subtle Grain" } },
  { id:"kurosawa-epic", title:"Akira Kurosawa", category:"Cinematic", desc:"Epic tableau, weather.", data:{ genre:"cinematic", camera:"Mitchell BNC", lens:"300mm tele", focal:300, aperture:"f/11", shutter:"1/48s", iso:"100", lighting:"Soft Overcast", composition:"Wide Establishing", vibe:"Akira Kurosawa style, epic tableau framing, telephoto compression to stack armies/crowds, strong weather like rain fog wind, layered depth, disciplined wides.", lensChar:"Vintage Softness", film:"B&W Negative", wb:"Daylight Balanced", grain:"Medium Texture" } },
  { id:"wet-plate", title:"Wet Plate Collodion", category:"Analog Vault", desc:"1850s ghostly chemical imperfection.", data:{ genre:"portrait", camera:"Large Format 8x10", lens:"300mm prime", focal:300, aperture:"f/5.6", shutter:"4s", iso:"1", lighting:"Natural Light", composition:"Centered", lightingSetups:["window side light, soft falloff"], vibe:"Wet plate collodion process (1850s), ghostly silver nitrate texture, chemical stains and poured edges, extremely shallow depth of field, eyes rendered pale/white due to UV sensitivity, antique sepia monochrome.", lensChar:"Vintage Softness", film:"Wet Plate Collodion", wb:"Cool Shade", grain:"Heavy Grit" } },
  { id:"kodachrome-64", title:"Kodachrome 64", category:"Analog Vault", desc:"The National Geographic look.", data:{ genre:"street", camera:"Nikon F3", lens:"35mm prime", focal:35, aperture:"f/5.6", shutter:"1/125s", iso:"64", lighting:"Natural Light", composition:"Rule of Thirds", lightingSetups:[], vibe:"Kodachrome 64 film stock, iconic National Geographic aesthetic (80s), deep rich reds and yellows, high contrast, distinct archival sharpness, nostalgic vacation mood.", lensChar:"Clinical Sharp", film:"Kodachrome 64", wb:"Daylight Balanced", grain:"Subtle Grain" } },
  { id:"polaroid-sx70", title:"Polaroid SX-70", category:"Analog Vault", desc:"Soft, dreamy instant film.", data:{ genre:"portrait", camera:"Polaroid SX-70", lens:"116mm prime", focal:116, aperture:"f/8", shutter:"1/60s", iso:"100", lighting:"Direct Flash", composition:"Centered", lightingSetups:["hard direct flash, fast falloff shadows"], vibe:"Polaroid SX-70 instant film, creamy soft focus, warm chemical color cast, blown-out highlights, nostalgic memory, square format aesthetic.", lensChar:"Dreamy Bloom", film:"Polaroid 600", wb:"Warm Tungsten", grain:"Medium Texture" } },
  { id:"solarization", title:"Solarization (Man Ray)", category:"The Darkroom", desc:"Surreal inverted highlights.", data:{ genre:"portrait", camera:"Large Format 4x5", lens:"150mm prime", focal:150, aperture:"f/11", shutter:"1s", iso:"10", lighting:"Hard Strobe", composition:"Centered", lightingSetups:["high contrast rim lighting"], vibe:"Solarization effect (Sabattier effect), surreal reversal of tone, metallic skin, dark outlines around highlights, dreamlike high contrast monochrome.", lensChar:"Clinical Sharp", film:"Kodak Tri-X B&W", wb:"Cool Shade", grain:"Medium Texture" } },
  { id:"cyanotype", title:"Cyanotype (Blueprint)", category:"The Darkroom", desc:"Deep Prussian blue monochrome.", data:{ genre:"experimental", camera:"Contact Print", lens:"None", focal:0, aperture:"None", shutter:"30s", iso:"1", lighting:"Natural Light", composition:"Top-down Flat Lay", lightingSetups:[], vibe:"Cyanotype print, deep Prussian blue and white monochrome, high contrast, architectural blueprint aesthetic, botanical textures, sun-printed look.", lensChar:"Vintage Softness", film:"None", wb:"Cool Shade", grain:"Heavy Grit" } },
  { id:"cross-process", title:"Cross-Processed", category:"The Darkroom", desc:"90s skate style, skewed colors.", data:{ genre:"street", camera:"Contax T2", lens:"38mm prime", focal:38, aperture:"f/5.6", shutter:"1/250s", iso:"400", lighting:"Direct Flash", composition:"Low Angle Hero", lightingSetups:["hard direct flash, fast falloff shadows"], vibe:"Cross-processed film look (slide film in C-41 chemicals), high contrast, skewed colors with yellow highlights and blue shadows, 90s skate magazine aesthetic.", lensChar:"Clinical Sharp", film:"Kodak Ektachrome", wb:"Mixed Lighting", grain:"Medium Texture" } },
  { id:"cyberpunk-neon", title:"Cyberpunk / Neo-Noir", category:"Genre Cinema", desc:"Rain, neon, high tech, low life.", data:{ genre:"night", camera:"Arri Alexa LF", lens:"35mm anamorphic", focal:35, aperture:"f/2", shutter:"1/48s", iso:"1600", lighting:"Neon Practical", composition:"Leading Lines", lightingSetups:["neon sign spill","atmospheric smoke and light shafts"], vibe:"Cyberpunk Neo-Noir aesthetic, rain-slicked streets reflecting pink and blue neon, high contrast, wet texture, steam and smoke, futuristic urban decay, anamorphic lens flares.", lensChar:"Clinical Sharp", film:"Kodak Vision3 500T", wb:"Mixed Lighting", grain:"Medium Texture" } },
  { id:"folk-horror", title:"Folk Horror", category:"Genre Cinema", desc:"Dread in bright daylight.", data:{ genre:"cinematic", camera:"Arri Alexa 35", lens:"24mm prime", focal:24, aperture:"f/8", shutter:"1/125s", iso:"200", lighting:"High Key White Cyc", composition:"Symmetrical Arch", lightingSetups:["high key white cyc, even wraparound light"], vibe:"Folk Horror aesthetic (Midsommar style), uncomfortably bright daylight, pastel florals, white linens, blinding sun, pagan symbolism, dread concealed by beauty, overexposed highlights.", lensChar:"Clinical Sharp", film:"Kodak Vision3 250D", wb:"Daylight Balanced", grain:"Clean/No Grain" } },
  { id:"space-opera", title:"Space Opera (70s)", category:"Genre Cinema", desc:"Practical models, lens flares.", data:{ genre:"cinematic", camera:"Panavision PSR", lens:"50mm anamorphic", focal:50, aperture:"f/4", shutter:"1/48s", iso:"100", lighting:"Hard Strobe", composition:"Wide Establishing", lightingSetups:["rim light, edge definition"], vibe:"70s Space Opera aesthetic (Star Wars / Alien), practical model effects, star fields, sterile white corridors, industrial sci-fi texture, anamorphic lens flares, matte painting backgrounds.", lensChar:"Vintage Softness", film:"Kodak 5247 100T", wb:"Cool Shade", grain:"Medium Texture" } },
  { id:"fisheye-90s", title:"Fisheye (90s Music Video)", category:"Extreme Perspectives", desc:"Circular distortion, world-bending.", data:{ genre:"experimental", camera:"Sony VX1000", lens:"8mm fisheye", focal:8, aperture:"f/4", shutter:"1/60s", iso:"400", lighting:"Direct Flash", composition:"Tight Close-up", lightingSetups:[], vibe:"Fisheye lens distortion, Hype Williams music video aesthetic, massive curvature of straight lines, exaggerated close-up features, circular vignette, Sony VX1000 texture.", lensChar:"Heavy Vignette", film:"Digital Video Tape", wb:"Mixed Lighting", grain:"Medium Texture" } },
  { id:"drone-topdown", title:"Top-Down Drone", category:"Extreme Perspectives", desc:"God's eye view geometry.", data:{ genre:"landscape", camera:"DJI Mavic 3", lens:"24mm prime", focal:24, aperture:"f/5.6", shutter:"1/500s", iso:"100", lighting:"Natural Light", composition:"Top-down Flat Lay", lightingSetups:[], vibe:"Top-down drone photography, perfect geometric patterns from above, flat lay of landscape or crowds, high altitude perspective, even sharpness edge-to-edge.", lensChar:"Clinical Sharp", film:"None", wb:"Daylight Balanced", grain:"Clean/No Grain" } },
  { id:"micro-macro", title:"Micro-Macro (Insect Eye)", category:"Extreme Perspectives", desc:"Alien textures, razor depth.", data:{ genre:"wildlife", camera:"Canon EOS R5 II", lens:"100mm macro", focal:100, aperture:"f/16", shutter:"1/200s", iso:"100", lighting:"Soft Overcast", composition:"Tight Close-up", lightingSetups:["ring light fill"], vibe:"Extreme macro photography, 2:1 magnification, alien textures of insect eyes or water drops, razor-thin depth of field, soft diffuse lighting to reveal microscopic detail.", lensChar:"Clinical Sharp", film:"None", wb:"Daylight Balanced", grain:"Clean/No Grain" } },
  { id:"technicolor", title:"Technicolor 3-Strip", category:"Color Eras", desc:"Hyper-saturated 1939 look.", data:{ genre:"cinematic", camera:"Technicolor 3-Strip Camera", lens:"35mm prime", focal:35, aperture:"f/2.8", shutter:"1/48s", iso:"5", lighting:"Hard Strobe", composition:"Centered", lightingSetups:["high key white cyc, even wraparound light"], vibe:"Technicolor 3-Strip process (Wizard of Oz era), hyper-saturated unreal reds and greens, low contrast but very bright, dye-transfer look, golden age of Hollywood studio lighting, extreme amount of light required.", lensChar:"Dreamy Bloom", film:"Technicolor Three-Strip", wb:"Warm Tungsten", grain:"Clean/No Grain" } },
  { id:"autochrome", title:"Autochrome Lumière", category:"Color Eras", desc:"1907 pointillist potato starch.", data:{ genre:"portrait", camera:"Large Format 4x5", lens:"150mm prime", focal:150, aperture:"f/5.6", shutter:"2s", iso:"5", lighting:"Natural Light", composition:"Centered", lightingSetups:[], vibe:"Autochrome Lumière (1907), first color photography process, pointillist painting look due to potato starch grain, pastel colors, soft focus, ethereal and dreamlike, long exposure.", lensChar:"Vintage Softness", film:"Autochrome Plate", wb:"Daylight Balanced", grain:"Heavy Grit" } },
  { id:"infrared-aero", title:"Infrared Aerochrome", category:"Experimental", desc:"Surreal pink foliage.", data:{ genre:"landscape", camera:"Hasselblad 500C/M", lens:"50mm prime", focal:50, aperture:"f/8", shutter:"1/250s", iso:"400", lighting:"Natural Light", composition:"Wide Establishing", lightingSetups:[], vibe:"Kodak Aerochrome Infrared film, surreal color shift, green foliage rendered as vibrant hot pink/red, deep dark blue skies, dreamlike high contrast.", lensChar:"Clinical Sharp", film:"Kodak Aerochrome", wb:"Daylight Balanced", grain:"Medium Texture" } },
  { id:"tilt-shift-mini", title:"Tilt-Shift Miniature", category:"Experimental", desc:"Faking a miniature world.", data:{ genre:"architecture", camera:"Canon EOS R5 II", lens:"45mm tilt-shift", focal:45, aperture:"f/2.8", shutter:"1/500s", iso:"100", lighting:"Natural Light", composition:"High Angle", lightingSetups:[], vibe:"Tilt-Shift photography, selective focus plane, blurring top and bottom to create a miniature 'toy world' effect, high angle city or crowd, vibrant saturation.", lensChar:"Clinical Sharp", film:"Digital", wb:"Daylight Balanced", grain:"Clean/No Grain" } },
  { id:"double-exposure", title:"Double Exposure", category:"Experimental", desc:"Silhouette landscape blend.", data:{ genre:"portrait", camera:"Canon EOS 5D Mark IV", lens:"50mm prime", focal:50, aperture:"f/8", shutter:"1/125s", iso:"100", lighting:"High Key White Cyc", composition:"Centered", lightingSetups:["high key white cyc, even wraparound light"], vibe:"Double Exposure art, silhouette of a subject filled with a secondary landscape image (forest or city), white background, surreal blending, True Detective intro style.", lensChar:"Clinical Sharp", film:"Digital", wb:"Daylight Balanced", grain:"Clean/No Grain" } },
  { id:"burkard-coast", title:"Chris Burkard", category:"Landscape", desc:"Cold coast, minimal palettes.", data:{ genre:"landscape", camera:"Sony A7R V", lens:"16-35mm wide", focal:16, aperture:"f/8", shutter:"1/320s", iso:"200", lighting:"Soft Overcast", composition:"Wide Establishing", vibe:"Chris Burkard style, cold coastal drama, minimal palettes, moody skies, tiny human scale against nature.", lensChar:"Clinical Sharp", film:"Digital", wb:"Cool Shade", grain:"Subtle Grain" } },
  { id:"adams-bw", title:"Ansel Adams", category:"Landscape", desc:"Epic B&W mountains.", data:{ genre:"landscape", camera:"Deardorff 8x10", lens:"300mm prime (8x10 eq)", focal:300, aperture:"f/64", shutter:"1s", iso:"25", lighting:"Natural Light", composition:"Leading Lines", vibe:"Ansel Adams style, dramatic black and white landscapes, Zone System tonal separation, crisp detail, large format clarity, deep red filter effect.", lensChar:"Clinical Sharp", film:"Kodak Tri-X B&W", wb:"Daylight Balanced", grain:"Clean/No Grain" } },
  { id:"sugimoto-minimal", title:"Hiroshi Sugimoto", category:"Landscape", desc:"Ultra-minimal long exposure.", data:{ genre:"landscape", camera:"Deardorff 8x10", lens:"300mm prime", focal:300, aperture:"f/45", shutter:"Bulb", iso:"100", lighting:"Natural Light", composition:"Centered", vibe:"Hiroshi Sugimoto style, minimal long exposure seascapes or theaters, smooth tonal gradients, contemplative distance, restrained monochrome.", lensChar:"Clinical Sharp", film:"Kodak Tri-X B&W", wb:"Daylight Balanced", grain:"Clean/No Grain" } },
  { id:"kenna-minimal", title:"Michael Kenna", category:"Landscape", desc:"Quiet monochrome, fog.", data:{ genre:"landscape", camera:"Hasselblad 500C/M", lens:"150mm prime", focal:150, aperture:"f/22", shutter:"30s", iso:"50", lighting:"Natural Light", composition:"Centered", vibe:"Michael Kenna style, minimalist long exposure landscapes, quiet geometry, fog or snow, deep blacks and soft highlights, square format.", lensChar:"Vintage Softness", film:"Kodak Tri-X B&W", wb:"Daylight Balanced", grain:"Subtle Grain" } },
  { id:"knowles-luxury", title:"John Knowles", category:"Product", desc:"Luxury glossy control.", data:{ genre:"product", camera:"Phase One XF IQ4", lens:"120mm macro", focal:120, aperture:"f/16", shutter:"1/125s", iso:"50", lighting:"Studio Softbox", composition:"Centered", lightingSetups:["cross-polarized lighting to control reflections","strip rim light, edge definition"], vibe:"High-end luxury product photography, controlled specular highlights, rich blacks, elegant negative space.", lensChar:"Clinical Sharp", film:"None", wb:"Daylight Balanced", grain:"Clean/No Grain", productSubgenre:"Luxury Jewelry Macro" } },
  { id:"brandl-packshot", title:"Karl Taylor", category:"Product", desc:"Clean ecommerce accuracy.", data:{ genre:"product", camera:"Hasselblad H6D", lens:"80mm prime", focal:80, aperture:"f/11", shutter:"1/125s", iso:"50", lighting:"High Key White Cyc", composition:"Centered", lightingSetups:["high key white cyc, even wraparound light"], vibe:"Clean ecommerce packshot, color accurate, minimal shadows, crisp edges, neutral background.", lensChar:"Clinical Sharp", film:"None", wb:"Daylight Balanced", grain:"Clean/No Grain", productSubgenre:"Ecommerce Packshot" } },
  { id:"kleiner-playful-stilllife", title:"Carl Kleiner", category:"Product", desc:"Geometric, colorful, playful.", data:{ genre:"product", camera:"Hasselblad X2D 100C", lens:"90mm prime", focal:90, aperture:"f/11", shutter:"1/125s", iso:"64", lighting:"Studio Softbox", composition:"Top-down Flat Lay", lightingSetups:["dual softbox symmetric lighting", "gradient sweep background, tabletop product lighting"], vibe:"Carl Kleiner style, vibrant geometric still life, clean color blocking, handmade objects, graphic precision.", lensChar:"Clinical Sharp", film:"Digital", wb:"Daylight Balanced", grain:"Clean/No Grain", productSubgenre:"Tabletop Styled" } },
  { id:"kander-editorial-polish", title:"Nadav Kander", category:"Product", desc:"Quiet, large-format polish.", data:{ genre:"product", camera:"Large Format 4x5", lens:"150mm prime", focal:150, aperture:"f/22", shutter:"1/15s", iso:"100", lighting:"Studio Softbox", composition:"Centered", lightingSetups:["softbox key plus bounce", "top down scrim, negative fill"], vibe:"Nadav Kander style, large-format stillness and editorial polish, restrained color, sculpted shadows, spacious negative space.", lensChar:"Vintage Softness", film:"Kodak Portra 400", wb:"Daylight Balanced", grain:"Subtle Grain", productSubgenre:"Luxury Jewelry Macro" } },
  { id:"illenberger-surreal-tabletop", title:"Sarah Illenberger", category:"Product", desc:"Cheerful, surreal objects.", data:{ genre:"product", camera:"Canon EOS R5 II", lens:"50mm prime", focal:50, aperture:"f/8", shutter:"1/125s", iso:"100", lighting:"High Key White Cyc", composition:"Asymmetric Framing", lightingSetups:["high key white cyc, even wraparound light", "backlit translucent diffusion, soft halos"], vibe:"Sarah Illenberger style, playful surreal product concepts, everyday objects turned into witty visual puns, vivid color.", lensChar:"Dreamy Bloom", film:"Digital", wb:"Daylight Balanced", grain:"Clean/No Grain", productSubgenre:"Tabletop Styled" } },
  { id:"koloskov-gloss", title:"Alex Koloskov", category:"Product", desc:"High-gloss premium product.", data:{ genre:"product", camera:"Phase One XF IQ4", lens:"120mm macro",focal:120,aperture:"f/22",shutter:"1/125s",iso:"50",lighting:"Hard Strobe",composition:"Tight Close-up",productSubgenre:"Tech Gadget Hero",lightingSetups:["cross-polarized lighting to control reflections","strip rim light, edge definition","gradient sweep background, tabletop product lighting"],vibe:"Alex Koloskov style, crisp product hero imagery, sculpted reflections, deep blacks and clean gradients.",lensChar:"Clinical Sharp",film:"Digital",wb:"Daylight Balanced",grain:"Clean/No Grain" } },
  { id:"belanger-minimal", title:"Peter Belanger", category:"Product", desc:"Clean Apple-like minimal.", data:{ genre:"product", camera:"Canon EOS R5 II", lens:"100mm macro",focal:100,aperture:"f/11",shutter:"1/160s",iso:"100",lighting:"High Key White Cyc",composition:"Centered",productSubgenre:"Tech Gadget Hero",lightingSetups:["high key white cyc, even wraparound light","softbox key plus bounce"],vibe:"Peter Belanger style, ultra-clean minimal product hero shots, soft controlled wrap light, seamless backgrounds, Apple advertising aesthetic.",lensChar:"Clinical Sharp",film:"Digital",wb:"Daylight Balanced",grain:"Clean/No Grain" } },
  { id:"hogan-speed", title:"Timothy Hogan", category:"Product", desc:"High-speed liquids.", data:{ genre:"product", camera:"Canon EOS R5 II", lens:"100mm macro",focal:100,aperture:"f/16",shutter:"1/4000s",iso:"800",lighting:"Hard Strobe",composition:"Tight Close-up",productSubgenre:"Beverage Condensation",lightingSetups:["strip rim light, edge definition","gradient sweep background, tabletop product lighting"],vibe:"Timothy Hogan style, high-speed tabletop liquids, crisp freeze, luminous gels and splashes, tight macro detail.",lensChar:"Clinical Sharp",film:"Digital",wb:"Daylight Balanced",grain:"Clean/No Grain" } },
  { id:"hargreaves-food", title:"Henry Hargreaves", category:"Product", desc:"Conceptual food still life.", data:{ genre:"product", camera:"Canon EOS 5D Mark IV", lens:"50mm prime",focal:50,aperture:"f/8",shutter:"1/125s",iso:"200",lighting:"Studio Softbox",composition:"Top-down Flat Lay",productSubgenre:"Food Editorial",lightingSetups:["top down scrim, negative fill"],vibe:"Henry Hargreaves style, concept-first food still life, clean tabletop geometry, editorial humor, soft directional studio light.",lensChar:"Vintage Softness",film:"Digital",wb:"Daylight Balanced",grain:"Subtle Grain" } },
  { id:"parker-poetic", title:"Olivia Parker", category:"Product", desc:"Quiet symbolic still life.", data:{ genre:"product", camera:"Large Format 4x5", lens:"210mm prime",focal:210,aperture:"f/22",shutter:"1/8s",iso:"100",lighting:"Natural Light",composition:"Leading Lines",productSubgenre:"Tabletop Styled",lightingSetups:["window side light, soft falloff"],vibe:"Olivia Parker style, poetic symbolic still life, gentle window light, carefully arranged objects with quiet narrative, split toning.",lensChar:"Vintage Softness",film:"Polaroid Type 55",wb:"Daylight Balanced",grain:"Subtle Grain" } },
  { id:"brassai-night", title:"Brassaï", category:"Night", desc:"Paris night, wet cobblestones.", data:{ genre:"night", camera:"Voigtländer Bergheil", lens:"105mm prime", focal:105, aperture:"f/4.5", shutter:"4s", iso:"25", lighting:"Neon Practical", composition:"Leading Lines", vibe:"Brassaï style, foggy night streets, wet reflections, noir mood, slow shutter ambience, deep shadows, magnesium flash powder feel.", lensChar:"Vintage Softness", film:"B&W Sheet Film", wb:"Mixed Lighting", grain:"Heavy Grit" } },
  { id:"shulman-midcentury-arch", title:"Julius Shulman", category:"Architecture", desc:"Clean mid-century hero shots.", data:{ genre:"architecture", camera:"Large Format 4x5", lens:"90mm wide", focal:90, aperture:"f/22", shutter:"1/15s", iso:"50", lighting:"Natural Light", composition:"Symmetrical Arch", lightingSetups:["window side light, soft falloff"], vibe:"Julius Shulman style, mid‑century modern hero shots, razor detail, corrected verticals, crisp daylight, black and white architectural mastery.", lensChar:"Clinical Sharp", film:"Kodak Tri-X B&W", wb:"Daylight Balanced", grain:"Clean/No Grain" } },
  { id:"baan-livedin-arch", title:"Iwan Baan", category:"Architecture", desc:"Documentary lived-in spaces.", data:{ genre:"architecture", camera:"Canon EOS R5 II", lens:"24-70mm zoom", focal:24, aperture:"f/5.6", shutter:"1/250s", iso:"800", lighting:"Natural Light", composition:"Rule of Thirds", vibe:"Iwan Baan style, documentary architecture, buildings shown as lived spaces, natural light only, candid human activity.", lensChar:"Clinical Sharp", film:"Digital", wb:"Daylight Balanced", grain:"Subtle Grain" } },
  { id:"stoller-clarity", title:"Ezra Stoller", category:"Architecture", desc:"Clean orthogonal hero shots.", data:{ genre:"architecture", camera:"Deardorff 8x10", lens:"90mm wide (8x10 eq)",focal:90,aperture:"f/64",shutter:"1s",iso:"25",lighting:"Natural Light",composition:"Symmetrical Arch",lightingSetups:[],vibe:"Ezra Stoller style, meticulous architectural documentation, parallel verticals, crisp mid-century modern clarity, calm daylight, deep focus.",lensChar:"Clinical Sharp",film:"Kodak Tri-X B&W",wb:"Daylight Balanced",grain:"Clean/No Grain" } },
  { id:"binet-poetry", title:"Hélène Binet", category:"Architecture", desc:"Deep shadow poetry.", data:{ genre:"architecture", camera:"Large Format 4x5", lens:"150mm prime",focal:150,aperture:"f/16",shutter:"1/60s",iso:"100",lighting:"Natural Light",composition:"Leading Lines",lightingSetups:[],vibe:"Hélène Binet style, architectural photography as light study, deep shadows, beams of sun, quiet human presence for scale, poetic abstraction.",lensChar:"Vintage Softness",film:"Kodak Tri-X B&W",wb:"Daylight Balanced",grain:"Subtle Grain" } },
  { id:"guerra-living", title:"Fernando Guerra", category:"Architecture", desc:"Warm lived-in architecture.", data:{ genre:"architecture", camera:"Canon EOS R5 II", lens:"16-35mm wide",focal:20,aperture:"f/5.6",shutter:"1/250s",iso:"400",lighting:"Natural Light",composition:"Wide Establishing",lightingSetups:[],vibe:"Fernando Guerra style, lived-in architecture with people and everyday motion, warm daylight, rich materials, balanced wide framing.",lensChar:"Clinical Sharp",film:"Digital",wb:"Daylight Balanced",grain:"Subtle Grain" } },
  { id:"hufton-crow", title:"Hufton + Crow", category:"Architecture", desc:"Crisp contemporary geometry.", data:{ genre:"architecture", camera:"Phase One XF IQ4", lens:"28mm wide",focal:28,aperture:"f/11",shutter:"1/125s",iso:"50",lighting:"Natural Light",composition:"Symmetrical Arch",lightingSetups:[],vibe:"Hufton + Crow style, clean contemporary architecture, precise lines, high dynamic range daylight, powerful scale and geometry.",lensChar:"Clinical Sharp",film:"Digital",wb:"Daylight Balanced",grain:"Clean/No Grain" } },
  { id:"attali-landscape", title:"Erieta Attali", category:"Architecture", desc:"Buildings as terrain.", data:{ genre:"architecture", camera:"Hasselblad 500C/M", lens:"50mm wide",focal:50,aperture:"f/8",shutter:"1/125s",iso:"100",lighting:"Golden Hour",composition:"Layered Depth",lightingSetups:[],vibe:"Erieta Attali style, architecture embedded in landscape, golden hour tones, long shadows, subtle atmosphere, calm cinematic wide framing.",lensChar:"Vintage Softness",film:"Kodak Portra 160",wb:"Daylight Balanced",grain:"Subtle Grain" } },
  { id:"basilico-rigor", title:"Gabriele Basilico", category:"Architecture", desc:"Urban rigor, cool monochrome.", data:{ genre:"architecture", camera:"Large Format 4x5", lens:"90mm wide",focal:90,aperture:"f/22",shutter:"1/30s",iso:"100",lighting:"Soft Overcast",composition:"Symmetrical Arch",lightingSetups:[],vibe:"Gabriele Basilico style, rigorous cityscapes, calm frontal viewpoints, ordered grids, soft overcast light, precise black and white tonality.",lensChar:"Clinical Sharp",film:"Kodak Tri-X B&W",wb:"Daylight Balanced",grain:"Subtle Grain" } },
  { id:"leifer-iconic-action", title:"Neil Leifer", category:"Sports", desc:"Iconic frozen action.", data:{ genre:"sports", camera:"Hasselblad 500C/M", lens:"80mm prime", focal:80, aperture:"f/5.6", shutter:"1/500s", iso:"100", lighting:"Stadium Lights", composition:"Low Angle Hero", lightingSetups:["stadium top light, crisp action freeze"], vibe:"Neil Leifer style, iconic peak‑moment sports frames, bright punchy color (Ali vs Liston), remote or low‑angle placement, perfectly timed action freeze, square format.", lensChar:"Clinical Sharp", film:"Kodak Ektachrome", wb:"Daylight Balanced", grain:"Clean/No Grain" } },
  { id:"iooss-commercial-sport", title:"Walter Iooss Jr.", category:"Sports", desc:"Clean commercial portraits.", data:{ genre:"sports", camera:"Canon EOS R3", lens:"24-70mm zoom", focal:50, aperture:"f/4", shutter:"1/1000s", iso:"400", lighting:"Studio Softbox", composition:"Rule of Thirds", lightingSetups:["softbox key plus bounce", "strip rim light, edge definition"], vibe:"Walter Iooss Jr. style, crisp commercial sports portraiture, athletes lit like icons, clean backgrounds, controlled studio light.", lensChar:"Clinical Sharp", film:"Digital", wb:"Daylight Balanced", grain:"Clean/No Grain" } },
  { id:"frissell-classic-sport", title:"Toni Frissell", category:"Sports", desc:"Classic daylight action.", data:{ genre:"sports", camera:"Rolleiflex 2.8F", lens:"80mm prime",focal:80,aperture:"f/11",shutter:"1/500s",iso:"100",lighting:"Natural Light",composition:"Low Angle Hero",lightingSetups:[],vibe:"Toni Frissell style, heroic sports moments, strong gesture and athletic form, clean outdoor light, decisive framing, low angle silhouette.",lensChar:"Clinical Sharp",film:"Kodak Ektachrome",wb:"Daylight Balanced",grain:"Subtle Grain" } },
  { id:"conlon-reportage", title:"Charles M. Conlon", category:"Sports", desc:"Early sports reportage.", data:{ genre:"sports", camera:"Graflex Series D", lens:"200mm prime",focal:200,aperture:"f/8",shutter:"1/500s",iso:"50",lighting:"Natural Light",composition:"Rule of Thirds",lightingSetups:[],vibe:"Charles M. Conlon style, reportage sports timing, clean framing of decisive athletic moments (Ty Cobb era), subtle grain and history.",lensChar:"Vintage Softness",film:"Nitrate Film",wb:"Daylight Balanced",grain:"Medium Texture" } },
  { id:"kluettmeier-si", title:"Heinz Kluetmeier", category:"Sports", desc:"Sports Illustrated era.", data:{ genre:"sports", camera:"Nikon F3", lens:"600mm prime",focal:600,aperture:"f/4",shutter:"1/1000s",iso:"400",lighting:"Stadium Lights",composition:"Rule of Thirds",lightingSetups:["stadium top light, crisp action freeze"],vibe:"Heinz Kluetmeier style, classic Sports Illustrated action, clean separation, bold color, frozen peak moments with clear backgrounds.",lensChar:"Clinical Sharp",film:"Kodachrome 64",wb:"Daylight Balanced",grain:"Clean/No Grain" } },
  { id:"chang-surf", title:"Aaron Chang", category:"Sports", desc:"Surf and ocean action.", data:{ genre:"sports", camera:"Nikon F5", lens:"300mm tele",focal:300,aperture:"f/5.6",shutter:"1/2000s",iso:"100",lighting:"Natural Light",composition:"Low Angle Hero",lightingSetups:[],vibe:"Aaron Chang style, surf and ocean action, bright coastal color, low angles near water, crisp splashes and lifestyle grit.",lensChar:"Clinical Sharp",film:"Kodachrome 64",wb:"Daylight Balanced",grain:"Subtle Grain" } },
  { id:"lanting-intimate-wildlife", title:"Frans Lanting", category:"Wildlife", desc:"Intimate nature storytelling.", data:{ genre:"wildlife", camera:"Nikon Z9", lens:"600mm prime", focal:600, aperture:"f/4", shutter:"1/1000s", iso:"800", lighting:"Golden Hour", composition:"Rule of Thirds", vibe:"Frans Lanting style, intimate wildlife storytelling, respectful distance yet emotional closeness, warm natural light.", lensChar:"Clinical Sharp", film:"Digital", wb:"Daylight Balanced", grain:"Subtle Grain" } },
  { id:"nicklen-dramatic-polar", title:"Paul Nicklen", category:"Wildlife", desc:"Dramatic polar and ocean.", data:{ genre:"wildlife", camera:"Sony Alpha 1", lens:"16-35mm wide", focal:16, aperture:"f/5.6", shutter:"1/1250s", iso:"1600", lighting:"Underwater Ambient", composition:"Leading Lines", lightingSetups:["underwater strobe fill, particle sparkle"], vibe:"Paul Nicklen style, dramatic polar and ocean wildlife, cold atmospheric light, spray and ice texture, underwater proximity.", lensChar:"Clinical Sharp", film:"Digital", wb:"Cool Shade", grain:"Medium Texture" } },
  { id:"vitale-conservation", title:"Ami Vitale", category:"Wildlife", desc:"Conservation storytelling.", data:{ genre:"wildlife", camera:"Nikon D850", lens:"24-70mm zoom",focal:35,aperture:"f/5.6",shutter:"1/250s",iso:"400",lighting:"Natural Light",composition:"Rule of Thirds",lightingSetups:[],vibe:"Ami Vitale style, conservation storytelling, intimate distance, human-animal relationships, warm natural color, respectful documentary tone.",lensChar:"Vintage Softness",film:"Digital",wb:"Daylight Balanced",grain:"Subtle Grain" } },
  { id:"sartore-ark", title:"Joel Sartore", category:"Wildlife", desc:"Studio wildlife portraits.", data:{ genre:"wildlife", camera:"Nikon D850", lens:"105mm macro",focal:105,aperture:"f/16",shutter:"1/250s",iso:"64",lighting:"Studio Softbox",composition:"Centered",lightingSetups:["softbox key plus bounce"],vibe:"Joel Sartore Photo Ark style, clean centered wildlife portraits, simple black or white backgrounds, direct gaze, clear taxonomy with empathy.",lensChar:"Clinical Sharp",film:"Digital",wb:"Daylight Balanced",grain:"Clean/No Grain" } },
  { id:"nichols-natgeo", title:"Nick Nichols", category:"Wildlife", desc:"Epic NatGeo wildlife.", data:{ genre:"wildlife", camera:"Canon EOS 1v", lens:"400mm prime",focal:400,aperture:"f/5.6",shutter:"1/500s",iso:"100",lighting:"Natural Light",composition:"Layered Depth",lightingSetups:[],vibe:"Nick Nichols style, epic NatGeo wildlife, strong environmental context, patient timing, natural color and dramatic light without exaggeration.",lensChar:"Clinical Sharp",film:"Kodachrome 64",wb:"Daylight Balanced",grain:"Subtle Grain" } },
  { id:"brandt-monochrome", title:"Nick Brandt", category:"Wildlife", desc:"Conservation monochrome.", data:{ genre:"wildlife", camera:"Pentax 67", lens:"105mm prime",focal:105,aperture:"f/4",shutter:"1/250s",iso:"100",lighting:"Soft Overcast",composition:"Centered",lightingSetups:[],vibe:"Nick Brandt style, black and white conservation portraiture, slow contemplative framing, animals as dignified subjects, subtle dust haze.",lensChar:"Vintage Softness",film:"Kodak Tri-X B&W",wb:"Daylight Balanced",grain:"Subtle Grain" } },
  { id:"skerry-marine", title:"Brian Skerry", category:"Wildlife", desc:"Underwater marine.", data:{ genre:"wildlife", camera:"Nikon D850", lens:"16mm fisheye",focal:16,aperture:"f/8",shutter:"1/250s",iso:"400",lighting:"Underwater Ambient",composition:"Wide Establishing",lightingSetups:["underwater strobe fill, particle sparkle"],vibe:"Brian Skerry style, underwater marine wildlife, wide-angle proximity, clear blue or green water, storytelling with scale and motion.",lensChar:"Clinical Sharp",film:"Digital",wb:"Cool Shade",grain:"Subtle Grain" } },
  { id:"mangelsen-wild", title:"Thomas D. Mangelsen", category:"Wildlife", desc:"Classic wilderness.", data:{ genre:"wildlife", camera:"Nikon F3", lens:"600mm prime",focal:600,aperture:"f/5.6",shutter:"1/500s",iso:"100",lighting:"Golden Hour",composition:"Rule of Thirds",lightingSetups:[],vibe:"Thomas D. Mangelsen style, classic wilderness scenes, dramatic golden light, clean silhouettes, patient timing and expansive habitat.",lensChar:"Clinical Sharp",film:"Fujichrome Velvia",wb:"Daylight Balanced",grain:"Subtle Grain" } }
];